NOISSUE - Update computation policies docs
ultravioletrs/prism-docs pull request #20
Opened 2024-05-31 10:59 UTC by smithjilks

2024-05-31 11:02 UTC, SammyOina requested changes

2024-05-31 11:02 UTC, SammyOina commented on docs/policies.md
> +1. Login as an Administrator and click on 'Computations' on the side navigation panel.
not just admin

2024-05-31 11:18 UTC, SammyOina approved these changes

2024-05-31 11:25 UTC, WashingtonKK requested changes

2024-05-31 11:29 UTC, WashingtonKK commented on docs/policies.md
> +![List Policies](img/ui/to computation policies.png)
![image](https://github.com/ultravioletrs/prism-docs/assets/43080232/ac2fdba2-2f28-443c-94db-0112b9c1e725)

The images do not display on my end.

2024-05-31 11:38 UTC, WashingtonKK approved these changes
LGTM

2024-08-07 13:56 UTC, SammyOina requested changes
update the images

2024-08-09 09:53 UTC, SammyOina requested changes

2024-08-09 09:53 UTC, SammyOina commented on docs/img/ui/computation policies.png
remove this file

2024-08-09 09:53 UTC, SammyOina commented on docs/img/ui/computations list.png
same here

2024-08-09 09:53 UTC, SammyOina commented on docs/img/ui/to computation policies.png
outdated image

2024-08-09 09:53 UTC, SammyOina commented on docs/img/ui/update policy page.png
same here

2024-08-23 12:48 UTC, SammyOina requested changes
please use a non-admin account for screenshots

2024-08-23 18:43 UTC, SammyOina approved these changes

2024-08-23 18:54 UTC, merged