DRAFT: PD-09 - Update billing docs
ultravioletrs/prism-docs pull request #22
Opened 2024-06-04 09:42 UTC by smithjilks

2024-06-04 15:26 UTC, SammyOina requested changes

2024-06-04 15:26 UTC, SammyOina commented on docs/billing.md
> +curl -sSiX POST https://prism.ultraviolet.rs/billing/createplan -H "Content-Type: application/json" -H "Authorization: Bearer <user_token>" -d @- << EOF
the docs are cutomer facing, only admin users (ultraviolet) should be able to do this, so this doc should be on the private repo

2024-06-04 15:26 UTC, SammyOina commented on docs/billing.md
>  ### Delete Plan
same goes for deleting plans

2024-06-04 15:26 UTC, SammyOina commented on docs/billing.md
>  ### Delete Plan
same goes for deleting plans

2024-06-04 15:26 UTC, SammyOina commented on docs/billing.md
>  ### Delete Plan
same goes for deleting plans

2024-06-04 15:26 UTC, SammyOina commented on docs/billing.md
>  ### Update Plan
same here, customers should only be able to list, view and subscribe to a plan

2024-06-04 15:26 UTC, SammyOina commented on docs/billing.md
>  ### Update Plan
and set their customer details and update them

2024-06-04 15:26 UTC, SammyOina commented on docs/billing.md
>  ### Update Plan
and set their customer details and update them

2024-06-05 11:09 UTC, SammyOina requested changes

2024-06-05 11:09 UTC, SammyOina commented on docs/billing.md
>  Currently, billing plans are only based on the maximum number of computations that an organization or user can have in the system. When an admin creates a plan, they limit the amount of computations
please also update this to be customer facing

2024-08-08 07:13 UTC, SammyOina approved these changes
remove curl and leave only ui
also remove all admin parts and leave only customer facing parts

2024-08-09 09:58 UTC, SammyOina requested changes

2024-08-09 09:58 UTC, SammyOina commented on docs/img/ui/update customer dialog.png
outdated

2024-08-09 09:58 UTC, SammyOina commented on docs/img/ui/plans list.png
remove admin related items from docs

2024-08-09 09:58 UTC, SammyOina commented on docs/img/ui/edit plan page.png
same here

2024-08-09 09:58 UTC, SammyOina commented on docs/img/ui/create plan dialog.png
same

2024-08-09 09:58 UTC, SammyOina commented on docs/img/ui/create customer dialog.png
also out of date

2024-08-09 09:58 UTC, SammyOina commented on docs/img/ui/create customer dialog.png
also out of date

2024-08-09 09:58 UTC, SammyOina commented on docs/img/ui/admin page.png
remove

2024-08-23 18:48 UTC, SammyOina approved these changes

2024-08-23 18:50 UTC, SammyOina requested changes
update the images some of these still mention organizations rather than workspaces

2024-08-23 18:50 UTC, SammyOina commented on docs/img/ui/checkout page.png
switch this image

2024-08-23 18:50 UTC, SammyOina commented on docs/img/ui/billing plans.png
same here

2024-08-23 18:50 UTC, SammyOina commented on docs/img/ui/billing customer.png
same here

2024-08-26 11:35 UTC, SammyOina approved these changes

2024-08-28 12:52 UTC, dborovcanin commented
@smithjilks Please resolve conflicts.

2024-08-29 20:39 UTC, merged