PD-25: Add Backend Info Docs
ultravioletrs/prism-docs pull request #26
Opened 2024-08-13 13:12 UTC by WashingtonKK

This adds docs for the recently added feature: https://github.com/ultravioletrs/prism/issues/312

Additionally, this enhances the backends docs by:

- Removing curl commands from docs
- Updating the images on the backends page.

- Related issue: #24
- Resolves: #25

2024-08-14 11:12 UTC, SammyOina requested changes

2024-08-14 11:12 UTC, SammyOina commented on docs/backends.md
> +## View Backend Information
include information on what this json file is used for on cocos and explain the fields it contains

2024-08-14 11:12 UTC, SammyOina commented on docs/img/delete_backend_1.png
use non-admin images

2024-08-14 13:07 UTC, WashingtonKK commented on docs/img/delete_backend_1.png
Solved in: https://github.com/ultravioletrs/prism-docs/pull/28

2024-08-14 13:26 UTC, SammyOina requested changes

2024-08-14 13:26 UTC, SammyOina commented on docs/backends.md
> +The backend_info.json file is useful in cocos when performing attestation. The file is provided to [cocos-cli](https://docs.cocos.ultraviolet.rs/cli/#backend-info) which can add measurement data or h
attested tls, we do not use it to perform attestation

2024-08-14 13:26 UTC, SammyOina commented on docs/backends.md
> +The backend_info.json file is useful in cocos when performing attestation. The file is provided to [cocos-cli](https://docs.cocos.ultraviolet.rs/cli/#backend-info) which can add measurement data or h
it can also be used to verify attestation report. Also link to cocos docs where relevant

2024-08-15 07:06 UTC, SammyOina requested changes

2024-08-15 07:06 UTC, SammyOina commented on docs/backends.md
> +An individual backend can be viewed on ui where it's details such as address, status, ID, certs and information can be acquired. Backend termination is also done on this page through cert revocation.
cert revocation is not always equal to termination, also just mention that this page includes cert management

2024-08-15 07:06 UTC, SammyOina commented on docs/backends.md
> +```
use the raw json example

2024-08-15 09:42 UTC, SammyOina approved these changes

2024-08-15 11:45 UTC, dborovcanin commented on docs/backends.md
> +For a SEV enabled backend, the backend information can be viewed using prism. This information is measured by a rust script found [here](https://github.com/ultravioletrs/cocos/blob/main/scripts/backe
Rust.. can be measured by Prism...

2024-08-15 11:49 UTC, dborovcanin commented on docs/backends.md
> +Manual backend termination can not be done directly on ui, but can be done using the curl command below:
...can not be done through the graphical user interface, but can be done using the HTTP API:

2024-08-15 11:50 UTC, dborovcanin commented on docs/backends.md
> +Alternatively, the backend can be deleted on the list backends page by clicking the trash icon:
...on the backends list page...

2024-08-23 13:06 UTC, merged