PD-46 - Refactor users page
ultravioletrs/prism-docs pull request #58
Opened 2024-11-28 08:09 UTC by WashingtonKK

# What type of PR is this?

## What does this do?

## Which issue(s) does this PR fix/relate to?

## Have you included tests for your changes?

## Did you document any new/modified features?

### Notes

2024-11-28 08:44 UTC, SammyOina requested changes

2024-11-28 08:44 UTC, SammyOina commented on docs/users.md
use images where possible, for example user creation/regsitration

2024-11-28 08:44 UTC, SammyOina commented on docs/users.md
document login and other user operations

2024-11-28 08:44 UTC, SammyOina commented on docs/users.md
document changing user passwords, account deactivation and removing themselves from workspaces etc

2024-12-04 16:55 UTC, SammyOina requested changes

2024-12-04 16:55 UTC, SammyOina commented on docs/users.md
Update the relevant section that is plainly curl commands to incoorporate UI images

2024-12-04 17:07 UTC, WashingtonKK commented on docs/users.md
These are all documented on the section below. The user can not obtain token from ui so this section will have to remain without images

2024-12-05 11:42 UTC, SammyOina requested changes

2024-12-05 11:42 UTC, SammyOina commented on docs/users.md
add login to create token section

2024-12-05 14:56 UTC, SammyOina approved these changes

2024-12-05 15:01 UTC, merged